mysite/members/urls.py
from django.urls import path
from . import views
from django.contrib.auth import  views as auth_views

app_name = 'members'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('edit_profile/', views.UserEditView.as_view(), name='edit_profile'),
    path('password/', views.PasswordEditView.as_view(template_name='registration/change_password.html')),
    path('<int:pk>/profile/', views.ProfilePageView.as_view(), name='profile_page'),
    path('<int:pk>/edit_profile_page/', views.EditProfilePageView.as_view(), name='edit_profile_page'),
    path('create_profile_page/', views.CreateProfilePageView.as_view(), name='create_profile_page'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('polls/', include('polls.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # ex: /posts/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /posts/5/
    path('<int:pk>/', views.PostPage.as_view(), name='post_page'),
    path('add_post/', views.AddPost.as_view(), name='add_post'),
    path('edit_post/<int:pk>', views.EditPost.as_view(), name='edit_post'),
    path('delete_post/<int:pk>', views.DeletePost.as_view(), name='delete_post'),
    path('category/<str:cats>/', views.CategoryPage, name='category'),
    path('vote/<int:pk>', views.VoteView, name='vote_post'),
    path('add_comment/<int:pk>', views.AddCommentView.as_view(), name='add_comment'),
]

mysite/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('posts:index')

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = RichTextField(blank=True, null=True, max_length=5000)
    profile_pic = models.ImageField(null=True, blank=True, upload_to='uploads/profile')
    website_url = models.CharField(max_length=255, null=True, blank=True)
    facebook_url = models.CharField(max_length=255, null=True, blank=True)
    twitter_url = models.CharField(max_length=255, null=True, blank=True)
    instagram_url = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('posts:index')

class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post_title = models.CharField(max_length=50)
    post_image = models.ImageField(null=True, blank=True, upload_to='uploads/images')
    post_description = RichTextField(blank=True, null=True, max_length=5000)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    votes = models.ManyToManyField(User, related_name='news_posts')

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse('posts:index')

    def total_votes(self):
        return self.votes.count()


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    comment_text = models.TextField(max_length=280)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.comment_text

mysite/posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('user', 'category', 'post_title', 'post_image', 'post_description')
        widgets = {
            'user': forms.TextInput(attrs={'class': 'form-control', 'value':'', 'id':'author_input', 'type':'hidden'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'post_title': forms.TextInput(attrs={'class': 'form-control'}),
            'post_description': forms.Textarea(attrs={'class': 'form-control'}),
        }

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_text',)
        widgets = {
            'comment_text': forms.Textarea(attrs={'class': 'form-control'}),
        }

mysite/posts/views.py
from django.views import generic
from django.urls import reverse_lazy, reverse
from .models import Post, Category, Comment
from .forms import PostForm, AddCommentForm
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect

class IndexView(generic.ListView):
    template_name = 'posts/index.html'
    context_object_name = 'latest_posts_list'

    def get_context_data(self, **kwargs):
        cat_menu = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context['cat_menu'] = cat_menu
        return context

    def get_queryset(self):
        """Return the last ten published posts."""
        return Post.objects.order_by('-pub_date')[:10]

class PostPage(generic.DetailView):
    model = Post
    template_name = 'posts/post_page.html'

    def get_context_data(self, **kwargs):
        cat_menu = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context['cat_menu'] = cat_menu

        data = get_object_or_404(Post, id=self.kwargs['pk'])
        total_votes = data.total_votes()
        context['total_votes'] = total_votes

        upvoted = False
        if data.votes.filter(id=self.request.user.id).exists():
            upvoted = True
        context['upvoted'] = upvoted

        return context

class AddPost(generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/add_post.html'

    def get_context_data(self, **kwargs):
        cat_menu = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context['cat_menu'] = cat_menu
        return context

class AddCommentView(generic.CreateView):
    model = Comment
    form_class = AddCommentForm
    template_name = 'posts/add_comment.html'
    success_url = reverse_lazy('posts:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

class EditPost(generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/update_post.html'

    def get_context_data(self, **kwargs):
        cat_menu = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context['cat_menu'] = cat_menu
        return context

class DeletePost(generic.DeleteView):
    model = Post
    template_name = 'posts/delete_post.html'
    success_url = reverse_lazy('posts:index')

    def get_context_data(self, **kwargs):
        cat_menu = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context['cat_menu'] = cat_menu
        return context

def VoteView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))

    if post.votes.filter(id=request.user.id).exists():
        post.votes.remove(request.user)

    else:
        post.votes.add(request.user)

    return HttpResponseRedirect(reverse('posts:post_page', args=[str(pk)]))

def CategoryPage(request, cats):

    newCats = cats.replace('-', ' ')
    category_posts = Post.objects.filter(category__name__contains=newCats)
    return render(request, 'posts/categories.html', {'cats':newCats.title(), 'category_posts':category_posts})

mysite/posts/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>
      {% block title %}
      News Sphere
      {% endblock %}
    </title>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FF0000;">
  <div class="container-fluid">

    <a class="navbar-brand" href="{% url 'posts:index' %}">News Sphere</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:add_post' %}">Add Post</a>
          </li>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <li><a class="dropdown-item" href="{% url 'members:edit_profile' %}">Edit Profile Settings</a></li>
              {% if user.profile.id %}

                <li><a class="dropdown-item"
                       href="{% url 'members:edit_profile_page' user.profile.id %}">Edit Profile Page</a></li>

              <li><a class="dropdown-item" href="{% url 'members:profile_page' user.profile.id %}">Profile Page</a></li>

              {% else %}
                  <li><a class="dropdown-item"
                       href="{% url 'members:create_profile_page' %}">Create Profile Page</a></li>
              {% endif %}


            </ul>
          </div>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
          </li>

        {% else %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'members:register' %}">Create Account</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>

        {% endif %}

        {% if cat_menu %}
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

            {% for cat in cat_menu %}
                <li><a class="dropdown-item" href="{% url 'posts:category' cat.name|slugify %}"> {{ cat.name }} </a></li>
            {% endfor %}


          </ul>
        </li>
        {% endif %}

      </ul>

      <form class="d-flex">
        {% if user.is_authenticated %}
          <a class="navbar-brand" >Welcome, {{ user.first_name }}!</a>
        {% endif %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
  </div>
</nav>

    <br>
    <div class="container">
    {% block content %}

    {% endblock %}
      </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>