mysite/members/urls.py
from django.urls import path
from . import views
from django.contrib.auth import  views as auth_views

app_name = 'members'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('edit_profile/', views.UserEditView.as_view(), name='edit_profile'),
    path('password/', views.PasswordEditView.as_view(template_name='registration/change_password.html')),
    path('<int:pk>/profile/', views.ProfilePageView.as_view(), name='profile_page'),
    path('<int:pk>/edit_profile_page/', views.EditProfilePageView.as_view(), name='edit_profile_page'),
    path('create_profile_page/', views.CreateProfilePageView.as_view(), name='create_profile_page'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('polls/', include('polls.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # ex: /posts/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /posts/5/
    path('<int:pk>/', views.PostPage.as_view(), name='post_page'),
    path('add_post/', views.AddPost.as_view(), name='add_post'),
    path('edit_post/<int:pk>', views.EditPost.as_view(), name='edit_post'),
    path('delete_post/<int:pk>', views.DeletePost.as_view(), name='delete_post'),
    path('category/<str:cats>/', views.CategoryPage, name='category'),
    path('vote/<int:pk>', views.VoteView, name='vote_post'),
    path('add_comment/<int:pk>', views.AddCommentView.as_view(), name='add_comment'),
]

mysite/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('posts:index')

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = RichTextField(blank=True, null=True, max_length=5000)
    profile_pic = models.ImageField(null=True, blank=True, upload_to='uploads/profile')
    website_url = models.CharField(max_length=255, null=True, blank=True)
    facebook_url = models.CharField(max_length=255, null=True, blank=True)
    twitter_url = models.CharField(max_length=255, null=True, blank=True)
    instagram_url = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('posts:index')

class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post_title = models.CharField(max_length=50)
    post_image = models.ImageField(null=True, blank=True, upload_to='uploads/images')
    post_description = RichTextField(blank=True, null=True, max_length=5000)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    votes = models.ManyToManyField(User, related_name='news_posts')

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse('posts:index')

    def total_votes(self):
        return self.votes.count()


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    comment_text = models.TextField(max_length=280)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.comment_text

mysite/posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('user', 'category', 'post_title', 'post_image', 'post_description')
        widgets = {
            'user': forms.TextInput(attrs={'class': 'form-control', 'value':'', 'id':'author_input', 'type':'hidden'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'post_title': forms.TextInput(attrs={'class': 'form-control'}),
            'post_description': forms.Textarea(attrs={'class': 'form-control'}),
        }

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_text',)
        widgets = {
            'comment_text': forms.Textarea(attrs={'class': 'form-control'}),
        }

mysite/posts/views.py
from django.views import generic
from django.urls import reverse_lazy, reverse
from .models import Post, Category, Comment
from .forms import PostForm, AddCommentForm
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect

class IndexView(generic.ListView):
    template_name = 'posts/index.html'
    context_object_name = 'latest_posts_list'

    def get_context_data(self, **kwargs):
        cat_menu = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context['cat_menu'] = cat_menu
        return context

    def get_queryset(self):
        """Return the last ten published posts."""
        return Post.objects.order_by('-pub_date')[:10]

class PostPage(generic.DetailView):
    model = Post
    template_name = 'posts/post_page.html'

    def get_context_data(self, **kwargs):
        cat_menu = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context['cat_menu'] = cat_menu

        data = get_object_or_404(Post, id=self.kwargs['pk'])
        total_votes = data.total_votes()
        context['total_votes'] = total_votes

        upvoted = False
        if data.votes.filter(id=self.request.user.id).exists():
            upvoted = True
        context['upvoted'] = upvoted

        return context

class AddPost(generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/add_post.html'

    def get_context_data(self, **kwargs):
        cat_menu = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context['cat_menu'] = cat_menu
        return context

class AddCommentView(generic.CreateView):
    model = Comment
    form_class = AddCommentForm
    template_name = 'posts/add_comment.html'
    success_url = reverse_lazy('posts:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

class EditPost(generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/update_post.html'

    def get_context_data(self, **kwargs):
        cat_menu = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context['cat_menu'] = cat_menu
        return context

class DeletePost(generic.DeleteView):
    model = Post
    template_name = 'posts/delete_post.html'
    success_url = reverse_lazy('posts:index')

    def get_context_data(self, **kwargs):
        cat_menu = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context['cat_menu'] = cat_menu
        return context

def VoteView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))

    if post.votes.filter(id=request.user.id).exists():
        post.votes.remove(request.user)

    else:
        post.votes.add(request.user)

    return HttpResponseRedirect(reverse('posts:post_page', args=[str(pk)]))

def CategoryPage(request, cats):

    newCats = cats.replace('-', ' ')
    category_posts = Post.objects.filter(category__name__contains=newCats)
    return render(request, 'posts/categories.html', {'cats':newCats.title(), 'category_posts':category_posts})

mysite/posts/templates/posts/add_comment.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <h1> Add Comment </h1>

    <div class="form-group">
        <form  method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success"> Add </button>
        </form>
    </div>

{% else %}

Error: Invalid access :(

{% endif %}

{% endblock %}

mysite/posts/templates/posts/add_post.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <h1> Add Post </h1>

    <div class="form-group">
        <form  method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button class="btn btn-success"> Add </button>
        </form>
    </div>

    <script>
        let name = "{{ user.id }}";
        document.getElementById("author_input").value = name;
    </script>

{% else %}

Error: Invalid access :(

{% endif %}

{% endblock %}

mysite/posts/templates/posts/categories.html
{% extends 'base.html' %}

{% block content %}

{% if category_posts %}
    <h1> {{ cats }} Category </h1>

    <ul>
        {% for post in category_posts %}
            <li>

                <a href="{% url 'posts:post_page' post.id %}">
                {{ post.post_title }}
                </a>

                by {{ post.user.first_name }} {{ post.user.last_name }}

                on {{ post.pub_date }}

                {% if user.is_authenticated %}
                    <small>
                        <a href="{% url 'posts:edit_post' post.id %}"> Edit </a>

                        <a href="{% url 'posts:delete_post' post.id %}"> Delete </a>
                    </small>
                {% endif %}

                <br/>
                {{ post.post_description|slice:":200" }}

            </li>
        {% endfor %}
        </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}

{% endblock %}

mysite/posts/templates/posts/delete_post.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated and user.id == post.user.id %}
    <h1> Delete Post "{{ post.post_title }}"? </h1>

    <div class="form-group">
        <form  method="post">
            {% csrf_token %}

            <button class="btn btn-success"> Delete Post </button>
        </form>
    </div>
{% else %}

Error: Invalid access :(

{% endif %}

{% endblock %}

mysite/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}

<h1> Posts </h1>
{% if latest_posts_list %}
    <ul class="list-group">
    {% for post in latest_posts_list %}
        <li class="list-group-item">

            <div class="d-flex w-100 justify-content-between">

                <small>
                    <a href="{% url 'posts:category' post.category.name|slugify %}">
                    {{ post.category.name }}</a>

                    | Posted by {{ post.user.first_name }} {{ post.user.last_name }}

                     {% if user.is_authenticated and user.id == post.user.id %}
                        <small>(
                            <a href="{% url 'posts:edit_post' post.id %}"> Edit </a>
                            |
                            <a href="{% url 'posts:delete_post' post.id %}"> Delete </a>
                            )
                        </small>
                    {% endif %}

                </small>

                {{ post.pub_date }}

             </div>

              <h5 class="mb-1">  <a href="{% url 'posts:post_page' post.id %}">
                {{ post.post_title }}
              </a> </h5>


            <br/>
            {{ post.post_description|slice:":200"|safe }}

        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}


{% endblock %}

mysite/posts/templates/posts/post_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ post.post_title }} {% endblock %}

{% block content %}


{% if post %}


        <h3>Post Category: {{ post.category.name }}</h3>
        <p> Posted by {{ post.user.first_name }}
            {{ post.user.last_name }} on {{ post.pub_date}}

             {% if user.is_authenticated and user.id == post.user.id %}
                <small>
                    (
                    <a href="{% url 'posts:edit_post' post.id %}"> Edit </a>
                    |
                    <a href="{% url 'posts:delete_post' post.id %}"> Delete </a>
                    )
                </small>
            {% endif %}
        </p>

        <h2>{{ post.post_title }}</h2>



        {% if post.post_image %}
            <img src="{{ post.post_image.url }}" class="img-fluid">
        {% endif %}

        <p> {{ post.post_description|safe }} </p>

        <form action="{% url 'posts:vote_post' post.pk %}" method="POST">
            {% csrf_token %}

            {% if user.is_authenticated %}
                {% if upvoted %}
                <button type="submit", name="post_id", value="{{ post.id }}", class="btn btn-danger btn-sm">
                    Down Vote </button>

                {% else %}
                <button type="submit", name="post_id", value="{{ post.id }}", class="btn btn-primary btn-sm">
                    Up Vote </button>

                {% endif %}
            {% else %}
            Log in to vote.

            {% endif %}

            | Up Votes: {{ total_votes }}
        </form>

        <br>
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row g-0">
            <div class="col-md-4">
                {% if post.user.profile.profile_pic %}
                    <img src="{{ post.user.profile.profile_pic.url }}" class="img-fluid rounded-start">

                {% else %}
                    <img src="{% static 'mysite/images/Default_pfp.jpg' %}" class="img-fluid rounded-start">
                {% endif %}


            </div>
            <div class="col-md-8">
              <div class="card-body">

                <h5 class="card-title">{{ post.user.first_name }} {{ post.user.last_name }}</h5>

                <p class="card-text"> {{ post.user.profile.bio|safe }} </p>

                <p class="card-text"><small class="text-muted">

                    <a href="{% url 'members:profile_page' post.user.profile.id %}"> Profile Page | </a>

                    {% if post.user.profile.website_url %}
                        <a href="{{ post.user.profile.website_url }}"> Website </a> |
                    {% endif %}

                    {% if post.user.profile.facebook_url %}
                        <a href="{{ post.user.profile.facebook_url }}"> Facebook </a> |
                    {% endif %}

                    {% if post.user.profile.twitter_url %}
                        <a href="{{ post.user.profile.twitter_url }}"> Twitter </a> |
                    {% endif %}

                    {% if post.user.profile.instagram_url %}
                        <a href="{{ post.user.profile.instagram_url }}"> Instagram </a>
                    {% endif %}

                </small></p>
              </div>
            </div>
          </div>
        </div>
        <br>
        <hr>
        <br>
        <h3>Comments:</h3>
        <br>
        {% if not post.comments.all %}
            No comments.
        {% else %}
            {% for comment in post.comments.all  %}


                <strong>
                    <p>{{ comment.user.first_name }} {{ comment.user.last_name }} - {{ comment.pub_date }}</p>

                </strong>
                <p> {{ comment.comment_text }} </p>


            {% endfor %}
        {% endif %}



    <a href="{% url 'posts:add_comment' post.pk %}" class="btn btn-primary">Add Comment</a>
{% else %}
    <p> Post not found.</p>
{% endif %}

<a href="{% url 'posts:index' %}" class="btn btn-secondary">Back</a>

{% endblock %}

mysite/posts/templates/posts/update_post.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated and user.id == post.user.id %}
    <h1> Edit Post </h1>

    <div class="form-group">
        <form  method="post">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button class="btn btn-success"> Update </button>
        </form>
    </div>
{% else %}

Error: Invalid access :(

{% endif %}


{% endblock %}